### ISSUE TITLE
"Optimize" the interaction with Pathfinder.

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/adroit#19]
Even though we moved the routing classes into an own independent package (which in the future might potentially be replaceable with a different router implementation) we still have some sort of coupling between Adroit and [Pathfinder](https://github.com/bitexpert/pathfinder). Even worse, because we are talking about an indirect coupling between both components. Let me go into details:

In Pathfinder we store the target (aka actionToken as we call it in Adroit) in the Request attributes. The ContainerAwareActionResolver of Adroit reads the target from the Request attributes and tries to look it up in the supplied DIC. Luckily the name of the used Request attribute is configurable right now but a developer needs to be aware of this. I would call this implicit coupling as Adroit depends on a Request attribute which needs to be stored first by a different component.

I`d like to see a change in the code of Adroit and Pathfinder to achieve a better de-coupling of both components.

**Comment by dropdevcoding** [comment]
Closed with #22
