### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by msphn** [bitExpert/adroit#6]
Provide the ability to use sessions.
Probably by using: https://github.com/Ocramius/PSR7Session

**Comment by geekishmatt** [comment]
Session is a persistence-specific logic, isn't it? In this case I'd suggest we keep ADR- and persistence-specific logic separated.

**Comment by msphn** [comment]
Indeed, we just talked about a SessionMiddleware, we even got a name for that. I close that ticket.
