### ISSUE TITLE
Improved routing

### ISSUE THREAD

**Issue by geekishmatt** [bitExpert/adroit#7]
Routing might be improved by adding optional regex-based pattern or datatype to the route declaration.
e.g.:

``` php
$baseUrl = 'http://myapp.loc:8080';
$router = new \bitExpert\Adroit\Router\RegexRouter($baseUrl);
$router->setRoutes([
        new Route('GET', [
                'route' => '/question/[:title]_[:id]',
                'params' => [
                        ':title' => ['type', 'string'],
                        ':id' => ['regex', '/[0-9]{1,}/']
                ]
        ], 'question')
]);
```

**Comment by msphn** [comment]
I would second that, like Silex did it with assert.

**Comment by dropdevcoding** [comment]
Instead of parameterizing we should implement a generic validation interface.
These Validators could also be used for replacing the former bF Validators for actions and so on. If there's no generic implementation (PSR-x), we could offer a package containing several validators.

``` php
$baseUrl = 'http://myapp.loc:8080';
$router = new \bitExpert\Adroit\Router\RegexRouter($baseUrl);
$router->setRoutes([
        new Route('GET', [
                'route' => '/question/[:title]_[:id]',
                'validators' => [
                        ':title' => new StringValidator(),
                        ':id' => [
                            new IntegerValidator(),
                            new MaxValueValidator(100)
                         ]
                ]
        ], 'question')
]);
```

I don't know if the route is implemented as immutable right now, but I would propose something like:

``` php
$router->setRoutes([
        new Route('/question/[:title]_[:id]')
            ->withMethod('GET')
            // ->withMethods(['GET', 'POST'])
            // ->withoutMethod('DELETE')
            // ->withoutMethods(['DELETE', 'OPTIONS'])
            ->withValidators('id', [
                new IntegerValidator(),
                new MaxValueValidator(100)
            ])
            //->withValidator('title', new TitleValidator()) 
            ->toAction('question')
]);
```

**Comment by shochdoerfer** [comment]
No need to over-engineer things. A simple regex matching routine should be enough. Sharing the domain object validation logic with url validation logic does not seem to make sense for me.

**Comment by dropdevcoding** [comment]
Well, it's not about overengineering but validating things. Since validation is always kind of same thing, no matter what the subjects are about in detail. In fact the subject is quite the same: We validate parameters.
