### ISSUE TITLE
Decouple Twig from Adroit

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/adroit#8]
It might be worthwhile to decouple Twig from Adroit and create an separate adroit-twig package _just_ for the TwigResponder.

**Comment by geekishmatt** [comment]
I'd suggest to decouple them. The TwigResponder bloats up the framework and is just another unnecessary dependency. From my point of view the JsonResponder should be enough.

**Comment by msphn** [comment]
Decouple but don't delete it. I'm using it.

**Comment by geekishmatt** [comment]
@cookiekiller What about a adroit-twig package (I'd suggest to call it bitexpert/twigastic)?
@shochdoerfer Was there any decision made?

**Comment by shochdoerfer** [comment]
I would love to do it but I am not sure if right now is a good time to do it as we haven`t gained much experience to understand if the Responder interface makes sense. I do not want to constantly change the interface and change the dependant packages as well. That would be way too much effort.

Ideally we would be able to find an agreement with @pmjones (and others) on a standard interface for actions, responders and the domain payload object to drive forward the collaboration between the different ADR implementations.

**Comment by dropdevcoding** [comment]
Twig integration has been moved to [bitexpert/adrenaline](https://github.com/bitExpert/adrenaline) where it will possibly become a separate package in near future (to discuss).

For Adroit this one is closed by #23
